# 通过此配置可以在 Docker 环境中学习 nginx 的各种指令

# 如果需要修改配置，验证配置是否生效， 可以通过 docker-compose 重新启动该容器 (或者 npm run learn:nginx )
version: '3'
services:
  learn-nginx:
    image: nginx:alpine
    ports:
      - 4000:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/usr/share/nginx/html