version: "3"
services: 
  domain:
    build:
      context: .
      dockerfile: router.Dockerfile
    labels:
      # 配置域名
      - "traefik.http.routers.cra.rule=Host(`cra.yemaoz.tech`)"
      
      # 配置 TLS
      # - traefik.http.routers.cra.tls=true
      # - traefik.http.routers.cra.tls.certresolver=le

# 一定要与 traefik 在同一网络下

networks:
  default:
    external:
      name: traefik-deploy_default