version: '3'

services: 
  whoami:
    image: containous/whoami
    labels:
      - "traefik.http.routers.whoami.rule=Host(`whoami.mojie.local`)"

networks:
  default:
    external:
      name: traefik-deploy_default